<a href="https://colab.research.google.com/github/sasiphatcha/PythonDataViz2026/blob/main/hw6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# HW6 673020639-5

##
1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด
2.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น
3. หาจำนวนผู้ป่วยที่เป็นคน "**คนต่างชาติเดินทางมาจากต่างประเทศ**

### ดึงไฟล์

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
path = "/content/drive/MyDrive/DataViz"
covid = os.path.join(path,'confirmed-cases-since-120465.csv')
print(covid)

/content/drive/MyDrive/DataViz/confirmed-cases-since-120465.csv

In [ ]:
data = pd.read_csv(covid)
data.head()

/tmp/ipykernel_7771/124259832.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(covid)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม

###1.   คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของข้อมูลทั้งหมด

ผู้หญิง

In [ ]:
data1 = data[['sex','age','province_of_isolation']]
data1

         sex   age province_of_isolation
0       หญิง  54.0             เชียงใหม่
1       หญิง  36.0             เชียงใหม่
2       หญิง  31.0             เชียงใหม่
3        ชาย  37.0             เชียงใหม่
4       หญิง  33.0             เชียงใหม่
...      ...   ...                   ...
356607   ชาย   NaN              พิษณุโลก
356608   ชาย   NaN              ปทุมธานี
356609  หญิง   NaN              ปทุมธานี
356610  หญิง   NaN              ปทุมธานี
356611   ชาย   NaN               ขอนแก่น

[356612 rows x 3 columns]

In [ ]:
female = data1[data1["sex"] == "หญิง"]
female

         sex   age province_of_isolation
0       หญิง  54.0             เชียงใหม่
1       หญิง  36.0             เชียงใหม่
2       หญิง  31.0             เชียงใหม่
4       หญิง  33.0             เชียงใหม่
5       หญิง  12.0             เชียงใหม่
...      ...   ...                   ...
356592  หญิง  27.0         กรุงเทพมหานคร
356595  หญิง  35.0         กรุงเทพมหานคร
356597  หญิง   NaN         กรุงเทพมหานคร
356609  หญิง   NaN              ปทุมธานี
356610  หญิง   NaN              ปทุมธานี

[203340 rows x 3 columns]

In [ ]:
# 1. แปลงคอลัมน์ age ให้เป็นตัวเลข (ข้อความที่ไม่ใช่ตัวเลขจะกลายเป็น NaN)
female['age'] = pd.to_numeric(female['age'], errors='coerce')
mean_age_fm = female['age'].mean()
print(mean_age_fm)

41.849625900589864

/tmp/ipykernel_7771/2403984497.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  female['age'] = pd.to_numeric(female['age'], errors='coerce')

ผู้ชาย

In [ ]:
male = data1[data1["sex"] == "ชาย"]
male

        sex   age province_of_isolation
3       ชาย  37.0             เชียงใหม่
6       ชาย  32.0             เชียงใหม่
9       ชาย  42.0             เชียงใหม่
11      ชาย  41.0             เชียงใหม่
13      ชาย  37.0             เชียงใหม่
...     ...   ...                   ...
356605  ชาย   NaN              พิษณุโลก
356606  ชาย   NaN              พิษณุโลก
356607  ชาย   NaN              พิษณุโลก
356608  ชาย   NaN              ปทุมธานี
356611  ชาย   NaN               ขอนแก่น

[135617 rows x 3 columns]

In [ ]:
# 1. แปลงคอลัมน์ age ให้เป็นตัวเลข (ข้อความที่ไม่ใช่ตัวเลขจะกลายเป็น NaN)
male['age'] = pd.to_numeric(male['age'], errors='coerce')
mean_age_m = male['age'].mean()
print(mean_age_m)

39.41913811289394

/tmp/ipykernel_7771/900756738.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  male['age'] = pd.to_numeric(male['age'], errors='coerce')

###2. คำนวณ อายุเฉลี่ย ของผู้หญิง และผู้ชาย ของผู้ป่วยในจังหวัดขอนแก่น

In [ ]:
kk_fm = female[female["province_of_isolation"] == "ขอนแก่น"]
kk_fm

         sex   age province_of_isolation
10537   หญิง  32.0               ขอนแก่น
10538   หญิง  56.0               ขอนแก่น
10540   หญิง   4.0               ขอนแก่น
10541   หญิง  41.0               ขอนแก่น
10543   หญิง  83.0               ขอนแก่น
...      ...   ...                   ...
350025  หญิง  48.0               ขอนแก่น
350027  หญิง  30.0               ขอนแก่น
350028  หญิง  24.0               ขอนแก่น
350029  หญิง  38.0               ขอนแก่น
350030  หญิง  27.0               ขอนแก่น

[8060 rows x 3 columns]

In [ ]:
kk_fm['age'].mean()

np.float64(40.69853950817626)

In [ ]:
kk_m = male[male["province_of_isolation"] == "ขอนแก่น"]
kk_m

        sex   age province_of_isolation
10539   ชาย   8.0               ขอนแก่น
10542   ชาย  67.0               ขอนแก่น
10553   ชาย  64.0               ขอนแก่น
10557   ชาย  73.0               ขอนแก่น
10560   ชาย  89.0               ขอนแก่น
...     ...   ...                   ...
350017  ชาย  41.0               ขอนแก่น
350022  ชาย  14.0               ขอนแก่น
350024  ชาย  52.0               ขอนแก่น
350026  ชาย  64.0               ขอนแก่น
356611  ชาย   NaN               ขอนแก่น

[4682 rows x 3 columns]

In [ ]:
kk_m['age'].mean()

np.float64(37.95105503589297)

###3. หาจำนวนผู้ป่วยที่เป็นคน "คนต่างชาติเดินทางมาจากต่างประเทศ"

In [ ]:
other = data[data['nationality'] != 'Thailand']
other

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
91,3905964,12/4/2022,11/4/2022,ชาย,69.0,ปี,NaN,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,หางดง
92,3905965,12/4/2022,11/4/2022,หญิง,28.0,ปี,NaN,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
226,3906099,12/4/2022,11/4/2022,หญิง,1.0,ปี,NaN,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
229,3906102,12/4/2022,11/4/2022,ชาย,13.0,ปี,NaN,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,หางดง
231,3906104,12/4/2022,11/4/2022,ชาย,70.0,ปี,NaN,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
...,...,...,...,...,...,...,...,...,...,...,...
356607,4262480,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,พิษณุโลก,ทัณฑสถาน/เรือนจำ,NaN,NaN
356608,4262481,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356609,4262482,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356610,4262483,1/5/2022,30/4/2022,หญิง,NaN,NaN,NaN,ปทุมธานี,ทัณฑสถาน/เรือนจำ,NaN,NaN
356611,4262484,1/5/2022,30/4/2022,ชาย,NaN,NaN,NaN,ขอนแก่น,ทัณฑสถาน/เรือนจำ,NaN,NaN

In [ ]:
data[(data['nationality'] != "Thailand") & (data['risk'] == "คนที่มาจากต่างประเทศ" ) ].shape

(0, 11)