<a href="https://colab.research.google.com/github/sasiphatcha/PythonDataViz2026/blob/main/hw7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# HW7 673020639-5

##สร้างตารางใหม่ที่ค่า sex เป็น missing ทั้งหมด

ดึงไฟล์

In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
path = "/content/drive/MyDrive/DataViz"
covid = os.path.join(path,'confirmed-cases-since-120465.csv')
print(covid)

/content/drive/MyDrive/DataViz/confirmed-cases-since-120465.csv

In [ ]:
data = pd.read_csv(covid)
data.head()

/tmp/ipykernel_1004/124259832.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(covid)

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
0,3905873,12/4/2022,11/4/2022,หญิง,54.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,จอมทอง
1,3905874,12/4/2022,11/4/2022,หญิง,36.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,เมืองเชียงใหม่
2,3905875,12/4/2022,11/4/2022,หญิง,31.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,ดอยหล่อ
3,3905876,12/4/2022,11/4/2022,ชาย,37.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,NaN,ต่างจังหวัด
4,3905877,12/4/2022,11/4/2022,หญิง,33.0,ปี,Thailand,เชียงใหม่,อยู่ระหว่างการสอบสวน,เชียงใหม่,แม่ริม

In [ ]:
data[pd.isnull(data["sex"])]

,No.,announce_date,Notified date,sex,age,Unit,nationality,province_of_isolation,risk,province_of_onset,district_of_onset
704,3906577,12/4/2022,11/4/2022,NaN,NaN,NaN,Thailand,ลำปาง,อยู่ระหว่างการสอบสวน,ลำปาง,เมืองลำปาง
705,3906578,12/4/2022,11/4/2022,NaN,NaN,NaN,Thailand,ลำปาง,อยู่ระหว่างการสอบสวน,ลำปาง,เมืองลำปาง
706,3906579,12/4/2022,11/4/2022,NaN,NaN,NaN,Thailand,ลำปาง,อยู่ระหว่างการสอบสวน,ลำปาง,เมืองลำปาง
707,3906580,12/4/2022,11/4/2022,NaN,NaN,NaN,Thailand,ลำปาง,อยู่ระหว่างการสอบสวน,ลำปาง,เมืองลำปาง
708,3906581,12/4/2022,11/4/2022,NaN,NaN,NaN,Thailand,ลำปาง,อยู่ระหว่างการสอบสวน,ลำปาง,เมืองลำปาง
...,...,...,...,...,...,...,...,...,...,...,...
353978,4259851,1/5/2022,30/4/2022,NaN,35.0,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,ดุสิต
353979,4259852,1/5/2022,30/4/2022,NaN,NaN,NaN,NaN,กรุงเทพมหานคร,อื่นๆ,กาฬสินธุ์,เมืองกาฬสินธุ์
353980,4259853,1/5/2022,30/4/2022,NaN,25.0,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,บางกอกใหญ่
353981,4259854,1/5/2022,30/4/2022,NaN,25.0,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,บางกอกใหญ่
353982,4259855,1/5/2022,30/4/2022,NaN,36.0,ปี,NaN,กรุงเทพมหานคร,อื่นๆ,กรุงเทพมหานคร,หนองจอก